### ISSUE TITLE
In Xamarin.Android getting error Java.Lang.NoSuchMethodError: no static method "Lorg/webrtc/EglBase;.create()Lorg/webrtc/EglBase;"

### ISSUE THREAD

**Issue by rameshkhatri** [dmariogatto/xamarin-webrtc#1]
Hi 

I just followed your project and created new project . It works fine for IOS but for android i am recieving below error . Can you please help what step i miss  with Android project

 Java.Lang.NoSuchMethodError: no static method "Lorg/webrtc/EglBase;.create()Lorg/webrtc/EglBase;"
  at Java.Interop.JniEnvironment+StaticMethods.GetStaticMethodID (Java.Interop.JniObjectReference type, System.String name, System.String signature) [0x0005b] in <9324da45a6654f83baffa7c2854d836a>:0
  at Java.Interop.JniType.GetStaticMethod (System.String name, System.String signature) [0x0000c] in <9324da45a6654f83baffa7c2854d836a>:0
  at Java.Interop.JniPeerMembers+JniStaticMethods.GetMethodInfo (System.String encodedMember) [0x00036] in <9324da45a6654f83baffa7c2854d836a>:0
  at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00000] in <9324da45a6654f83baffa7c2854d836a>:0
  at Xam.WebRtc.Android.EglBase.Create () [0x00002] in /Users/pc/Documents/AppRtc/xamarin-webrtc-master/src/Bindings/Xam.WebRtc.Android/obj/Debug/generated/src/Xam.WebRtc.Android.IEglBase.cs:420
  at TestWe.Code.WebRtcClient..ctor (Android.Content.Context context, Xam.WebRtc.Android.SurfaceViewRenderer remoteView, Xam.WebRtc.Android.SurfaceViewRenderer localView, TestWe.Code.IWebRtcObserver observer) [0x00070] in /Users/pc/Projects/TestWe/TestWe/Code/WebRtcClient.cs:91
  at TestWe.MainActivity.Init () [0x00113] in /Users/pc/Projects/TestWe/TestWe/MainActivity.cs:59
  at TestWe.MainActivity+<>c__DisplayClass4_0.<OnCreate>b__1 () [0x00024] in /Users/pc/Projects/TestWe/TestWe/MainActivity.cs:51
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021
  at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <a4eee078a8cb4ad1ab60303e59de6ebd>:0
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <a4eee078a8cb4ad1ab60303e59de6ebd>:0
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <a4eee078a8cb4ad1ab60303e59de6ebd>:0
  at at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.16(intptr,intptr)
  at java.lang.NoSuchMethodError: no static method "Lorg/webrtc/EglBase;.create()Lorg/webrtc/EglBase;
  at at mono.java.lang.RunnableImplementor.n_run(Native Method)
  at at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
  at at android.app.Activity.runOnUiThread(Activity.java:6347)
  at at crc648607fc34725d58d0.MainActivity.n_onCreate(Native Method)
  at at crc648607fc34725d58d0.MainActivity.onCreate(MainActivity.java:32)
  at at android.app.Activity.performCreate(Activity.java:7224)
  at at android.app.Activity.performCreate(Activity.java:7213)
  at at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
  at at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
  at at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
  at at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
  at at android.os.Handler.dispatchMessage(Handler.java:106)
  at at android.os.Looper.loop(Looper.java:201)
  at at android.app.ActivityThread.main(ActivityThread.java:6810)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by rameshkhatri** [comment]
Issue is fixed after adding below lines in xamarin android .csproj file

<AndroidEnableDesugar>True</AndroidEnableDesugar>
     <AndroidDexTool>d8</AndroidDexTool>
